export enum Status {
  PENDING = 'PENDING',
  REVIEWING = 'REVIEWING',
  CANCELLED = 'CANCELLED',
  WAITING_CUSTOMER_APPROVAL = 'WAITING_CUSTOMER_APPROVAL',
  WAITING_STOCK = 'WAITING_STOCK',
  REPAIRING = 'REPAIRING',
  WAITING_FOR_PICKUP = 'WAITING_FOR_PICKUP',
  FINISHED = 'FINISHED'
}
