version: '3'
services:
  api:
    build: .
    ports:
      - "3333:3333"
    environment:
      - PORT=3333
    depends_on:
      - mongo
      - redis
      - rabbitmq
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
  redis:
    image: "redis"
    ports:
      - "6379:6379"
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"
