version: '3'
services:
  api:
    build: .
    ports:
      - '3333:3333'
    environment:
      - PORT=3333
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongo
      - redis
      - rabbitmq
      - eventstore
      - mailcatcher
    volumes:
      - .:/fixtrack
    networks:
      - network

  mongo:
    image: 'mongo'
    ports:
      - '27017:27017'
    volumes:
      - type: volume
        source: mongo-volume-data
        target: /data/db
    networks:
      - network

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - '1080:1080' # Interfaz web
      - '1025:1025' # Puerto SMTP
    networks:
      - network

  eventstore:
    image: eventstore/eventstore:20.10.2-buster-slim
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_EXT_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - '1113:1113'
      - '2113:2113'
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore
    networks:
      - network

  redis:
    image: 'redis'
    restart: always
    command: ['redis-server', '/usr/local/etc/redis/redis.conf']
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - network
  rabbitmq:
    image: 'rabbitmq:management'
    ports:
      - '5672:5672'
      - '15672:15672'

networks:
  network:
    driver: bridge

volumes:
  mongo-volume-data:
  eventstore-volume-data:
  eventstore-volume-logs:
  cache:
    driver: local
