name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Instalar Docker Compose
      run: sudo apt-get install docker-compose

    - name: Construir y levantar contenedores
      run: |
        docker-compose build
        docker-compose up -d  # Ejecuta en modo "detached" para que el comando retorne inmediatamente
    - name: Esperar a que los servicios estén disponibles
      run: sleep 30
    - run: npm run test